services:
  frontend:
    image: "ghcr.io/cipherly-xyz/cipherly-frontend:latest"
    ports:
      - "8000:80"
  backend:
    image: "ghcr.io/cipherly-xyz/cipherly-backend:latest"
    environment:
      "DATABASE_URL": "sqlite:///data/db.sqlite"
    ports:
      - "3000:3000"
    volumes:
      - data:/data
  caddy:
      image: caddy:alpine
      environment:
        "HOSTNAME": ${HOSTNAME}
      ports:
        # Binding low ports might not work on all machines
        # with rootless docker
        - 80:80
        - 443:443
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
      restart: always

volumes:
  data:
  caddy_data:
  caddy_config: