services:
  frontend:
    image: "ghcr.io/tufteddeer/secretshare-frontend:latest"
    ports:
      - "8000:80"
  backend:
    image: "ghcr.io/tufteddeer/secretshare-backend:latest"
    environment:
      "DATABASE_URL": "sqlite:///data/db.sqlite"
    ports:
      - "3000:3000"
    volumes:
      - data:/data
  caddy:
      image: caddy:alpine
      ports:
        - 8080:80
        #- 443:443
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        # - ./certs:/data
      restart: always

volumes:
  data: