name: Create and publish Docker image

on:
  push:
    #tags:
    #  - "v*"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    strategy:
        matrix:
          component: ["frontend"] #, "backend"]
    env:
      IMAGE_NAME: ${{ github.repository }}-${{ matrix.component }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: ${{ matrix.component }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          
      - name: Extract artifacts
        run: |
          id=$(docker create ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }})
          docker cp $id:/srv artifacts
          docker rm -v $id
      - name: ls
        run: ls artifacts
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'artifacts/**'
          